### PR TITLE
Adding capture_log: true

### PR DESCRIPTION
**Pull request by andyduong1920**
https://github.com/nimblehq/elixir-templates/issues/89

## What happened

Start ExUnit with `capture_log: true` option
 
## Insight

https://elixirschool.com/blog/til-capture-log-in-exunit-tests/
 
## Proof Of Work

The test is passed

### CODE REVIEW

**Comment by hanam1ni** [comment]
How about we move the step that we update the `ExUnit.start` option after install all the addon? So we don't need to add the option in every addon and it will be easy to add other options in the future. Also, support when we want to update other modules.
```elixir
defp common_setup(%Project{} = project) do
    # Install addons ... 

    if install_addon_prompt?("Oban"), do: Addons.Oban.apply(project)
    if install_addon_prompt?("ExVCR"), do: Addons.ExVCR.apply(project)

    project
    |> update_test_helper()
    |> update_others() # In the future, we just pipe it.
end
```

**Comment by andyduong1920** [comment]
> How about we move the step that we update the `ExUnit.start` option after install all the addon? So we don't need to add the option in every addon and it will be easy to add other options in the future. Also, support when we want to update other modules.
> 
> ```elixir
> defp common_setup(%Project{} = project) do
>     # Install addons ... 
> 
>     if install_addon_prompt?("Oban"), do: Addons.Oban.apply(project)
>     if install_addon_prompt?("ExVCR"), do: Addons.ExVCR.apply(project)
> 
>     project
>     |> update_test_helper()
>     |> update_others() # In the future, we just pipe it.
> end
> ```

Do you mean moving on the updating `ExUnit.start()` step or the whole test_env addon at the end @hanam1ni ?

If we move only the updating `ExUnit.start()` step, what should we name for that addon 🤔  ExUnit addon 🤔

**Review by hanam1ni — APPROVED** [review]

**Comment by andyduong1920** [comment]
Oh I just merged https://github.com/nimblehq/elixir-templates/pull/95 to this branch 🙈. cc @byhbt

**Comment by andyduong1920** [comment]
> Oh I just merged #95 to this branch 🙈. cc @byhbt

@byhbt for the ExUnit addon, we just need to review 5 files, the other files came from #95 :( 

image

**Review by byhbt — APPROVED** [review]

**Pull request merged**
